### ISSUE TITLE
Add support for restore-keys with caching

### ISSUE THREAD

**Issue by rkoesters** [flatpak/flatpak-github-actions#57]
See [Matching a cache key](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) and [actions/toolkit/cache#restore-cache](https://github.com/actions/toolkit/tree/main/packages/cache#restore-cache).

**Comment by bilelmoussaoui** [comment]
That's already possible?

**Comment by bilelmoussaoui** [comment]
What's the use case here?

**Comment by rkoesters** [comment]
The use-case is to leverage the cache to try and speed up builds. If a cache doesn't exist for the exact `cache-key` provided, then the workflow can load an existing cache that matches the `restore-key` prefix. This eliminates the need to freshly download each dependency for each workflow build (for git sources this means the `git pull` just verifies there is nothing new to download; if there are changes, it just needs to download the deltas).

In theory, it could also be used to avoid recompiling bits of code that have not changed, however that would be build system specific, so I'd say its a bit out of scope for this request.

**Comment by bilelmoussaoui** [comment]
I mean that's what `cache-key` option provides for you already. The restore keys are hardcoded to the `flatpak-builder-` & `flatpak-` along with the `cache-key` that you define. The reason why we allow you to set one is because the action keeps complaining that an action already defined this cache key which is completely wrong (an issue is already open on the cache action side) and we suggest people to assign it to `flatpak-$git-commit-sha` to avoid the issue. 

I don't see what else we should provide

**Comment by bilelmoussaoui** [comment]
I am going to assume the latest releases should cover everything you might need for improving caching. Please re-open if that is not the case
